.PHONY: help validate preflight render deploy start-local run-operators clean status send watch e2e test-xtask

ENV ?= local
ENV_CONFIG ?= config/environments/$(ENV).json
DEPLOYMENTS_FILE ?= deployments/$(ENV).json
GENERATED_DIR ?= generated/$(ENV)
MSG ?= hello
TIMEOUT ?= 120

XTASK = cargo xtask --env $(ENV) --env-config $(ENV_CONFIG) --deployments $(DEPLOYMENTS_FILE) --generated-dir $(GENERATED_DIR)
XTASK_LOCAL = cargo xtask --env-config config/environments/local.json --deployments deployments/local.json --generated-dir generated/local

help:
	@echo "Parallel xtask entrypoints"
	@echo ""
	@echo "Environment: ENV=$(ENV)"
	@echo "  env config:   $(ENV_CONFIG)"
	@echo "  deployments:  $(DEPLOYMENTS_FILE)"
	@echo "  generated:    $(GENERATED_DIR)"
	@echo ""
	@echo "Native xtask targets:"
	@echo "  make -f Makefile.xtask validate"
	@echo "  make -f Makefile.xtask preflight"
	@echo "  make -f Makefile.xtask render"
	@echo "  make -f Makefile.xtask start-local"
	@echo "  make -f Makefile.xtask run-operators ENV=testnet"
	@echo "  make -f Makefile.xtask deploy"
	@echo "  make -f Makefile.xtask clean"
	@echo "  make -f Makefile.xtask status"
	@echo "  make -f Makefile.xtask send MSG=hello"
	@echo "  make -f Makefile.xtask watch"
	@echo "  make -f Makefile.xtask e2e MSG=hello"
	@echo "  make -f Makefile.xtask test-xtask"

validate:
	@$(XTASK) validate

preflight:
	@$(XTASK) preflight

render:
	@$(XTASK) render

deploy:
	@$(XTASK) deploy

start-local:
	@$(XTASK_LOCAL) start-local

run-operators:
	@$(XTASK) run-operators

clean:
	@$(XTASK) clean

status:
	@$(XTASK) status

send:
	@$(XTASK) msg send "$(MSG)"

watch:
	@$(XTASK) msg watch --timeout $(TIMEOUT)

e2e:
	@$(XTASK) msg e2e "$(MSG)" --timeout $(TIMEOUT)

test-xtask:
	@cargo test -p xtask
