#!/bin/sh
# Start Symbiotic relay sidecar with operator-specific configuration
#
# Usage: start-sidecar.sh <operator_index>
# Example: start-sidecar.sh 1
#
# Required environment variables (passed via per-operator sidecar-N.env):
#   DRIVER_ADDRESS       — Relay driver contract address (lowercased)
#   DRIVER_CHAIN_ID      — Chain ID where the driver is deployed
#   SOURCE_CHAIN_ID      — Source chain ID
#   SIDECAR_SECRET_KEYS  — Pre-computed secret keys string (generated by xtask)

set -e

OPERATOR_INDEX="${1:-1}"
STORAGE_DIR="/storage"

echo "=== Starting Relay Sidecar ${OPERATOR_INDEX} ==="

if [ -z "${DRIVER_ADDRESS:-}" ]; then
    echo "ERROR: DRIVER_ADDRESS env var is not set."
    echo "Ensure the environment JSON has deployments.relayInfra.driver populated."
    exit 1
fi
if [ -z "${DRIVER_CHAIN_ID:-}" ]; then
    echo "ERROR: DRIVER_CHAIN_ID env var is not set."
    exit 1
fi
if [ -z "${SIDECAR_SECRET_KEYS:-}" ]; then
    echo "ERROR: SIDECAR_SECRET_KEYS env var is not set."
    echo "Run 'cargo xtask start' to generate sidecar env files."
    exit 1
fi
if [ -z "${SOURCE_CHAIN_ID:-}" ]; then
    echo "ERROR: SOURCE_CHAIN_ID env var is not set."
    exit 1
fi

echo "Driver address: ${DRIVER_ADDRESS}"
echo "Driver chain ID: ${DRIVER_CHAIN_ID}"
echo "Source chain ID: ${SOURCE_CHAIN_ID}"

EVM_SOURCE_RPC="${EVM_SOURCE_RPC:-http://anvil:8545}"
EVM_DEST_RPC="${EVM_DEST_RPC:-http://anvil-settlement:8546}"
EVM_CHAINS="${EVM_SOURCE_RPC},${EVM_DEST_RPC}"

exec /app/relay_sidecar \
    --secret-keys "${SIDECAR_SECRET_KEYS}" \
    --storage-dir "${STORAGE_DIR}" \
    --api.listen "0.0.0.0:8080" \
    --p2p.listen "/ip4/0.0.0.0/tcp/8880" \
    --p2p.mdns \
    --p2p.dht-mode disabled \
    --sync.period 30s \
    --driver.chain-id "${DRIVER_CHAIN_ID}" \
    --driver.address "${DRIVER_ADDRESS}" \
    --evm.chains "${EVM_CHAINS}"
