#!/usr/bin/env bash
# Generate addresses.env from deployment data
#
# This script creates a shell-sourceable file with all deployed contract addresses.
# Run after deployment completes.
#
# Usage: ./scripts/generate-addresses.sh
#        make addresses

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEPLOY_DATA_DIR="${DEPLOY_DATA_DIR:-$PROJECT_ROOT/data/deploy-data}"
OUT_ENV="${OUT_ENV:-$DEPLOY_DATA_DIR/addresses.env}"

SOURCE_RPC_URL="${SOURCE_RPC_URL:-http://localhost:8545}"
DEST_RPC_URL="${DEST_RPC_URL:-http://localhost:8546}"

# Check dependencies
require() { command -v "$1" >/dev/null 2>&1 || { echo "ERROR: missing dependency: $1" >&2; exit 1; }; }
require jq

# Check required files exist
req_file() { [[ -f "$1" ]] || { echo "ERROR: missing file: $1" >&2; exit 1; }; }

req_file "$DEPLOY_DATA_DIR/source_contracts.json"
req_file "$DEPLOY_DATA_DIR/dest_contracts.json"

# Extract required addresses
SOURCE_CHAIN_ID="$(jq -er '.chainId' "$DEPLOY_DATA_DIR/source_contracts.json")"
DEST_CHAIN_ID="$(jq -er '.chainId' "$DEPLOY_DATA_DIR/dest_contracts.json")"
DVN_SOURCE_ADDRESS="$(jq -er '.dvn' "$DEPLOY_DATA_DIR/source_contracts.json")"
DVN_DEST_ADDRESS="$(jq -er '.dvn' "$DEPLOY_DATA_DIR/dest_contracts.json")"
SEND_ULN_ADDRESS="$(jq -er '.sendUln' "$DEPLOY_DATA_DIR/source_contracts.json")"
RECEIVE_ULN_ADDRESS="$(jq -er '.receiveUln' "$DEPLOY_DATA_DIR/dest_contracts.json")"
SETTLEMENT_ADDRESS="$(jq -er '.settlement' "$DEPLOY_DATA_DIR/dest_contracts.json")"

# Extract optional addresses (manual testing convenience)
TEST_OAPP_SOURCE_ADDRESS=""
TEST_OAPP_DEST_ADDRESS=""
if [[ -f "$DEPLOY_DATA_DIR/testoapp_source.json" ]]; then
    TEST_OAPP_SOURCE_ADDRESS="$(jq -er '.testOApp' "$DEPLOY_DATA_DIR/testoapp_source.json")"
fi
if [[ -f "$DEPLOY_DATA_DIR/testoapp_dest.json" ]]; then
    TEST_OAPP_DEST_ADDRESS="$(jq -er '.testOApp' "$DEPLOY_DATA_DIR/testoapp_dest.json")"
fi

LZ_ENDPOINT_SOURCE_ADDRESS=""
LZ_ENDPOINT_DEST_ADDRESS=""
if [[ -f "$DEPLOY_DATA_DIR/layerzero_source.json" ]]; then
    LZ_ENDPOINT_SOURCE_ADDRESS="$(jq -er '.endpoint' "$DEPLOY_DATA_DIR/layerzero_source.json")"
fi
if [[ -f "$DEPLOY_DATA_DIR/layerzero_dest.json" ]]; then
    LZ_ENDPOINT_DEST_ADDRESS="$(jq -er '.endpoint' "$DEPLOY_DATA_DIR/layerzero_dest.json")"
fi

mkdir -p "$DEPLOY_DATA_DIR"

cat > "$OUT_ENV" <<EOF
# Generated by scripts/generate-addresses.sh
# $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
# Source this file for manual testing:
#   source data/deploy-data/addresses.env

# RPCs
SOURCE_RPC_URL=$SOURCE_RPC_URL
DEST_RPC_URL=$DEST_RPC_URL

# Chains
SOURCE_CHAIN_ID=$SOURCE_CHAIN_ID
DEST_CHAIN_ID=$DEST_CHAIN_ID

# DVN
DVN_SOURCE_ADDRESS=$DVN_SOURCE_ADDRESS
DVN_DEST_ADDRESS=$DVN_DEST_ADDRESS

# ULN
SEND_ULN_ADDRESS=$SEND_ULN_ADDRESS
RECEIVE_ULN_ADDRESS=$RECEIVE_ULN_ADDRESS

# Settlement
SETTLEMENT_ADDRESS=$SETTLEMENT_ADDRESS

# TestOApp (for manual testing)
TEST_OAPP_SOURCE_ADDRESS=$TEST_OAPP_SOURCE_ADDRESS
TEST_OAPP_DEST_ADDRESS=$TEST_OAPP_DEST_ADDRESS

# LayerZero Endpoints
LZ_ENDPOINT_SOURCE_ADDRESS=$LZ_ENDPOINT_SOURCE_ADDRESS
LZ_ENDPOINT_DEST_ADDRESS=$LZ_ENDPOINT_DEST_ADDRESS
EOF

echo "Wrote $OUT_ENV"
