#!/bin/bash
# Setup script for Operator
#
# This script:
# 1. Creates directory structure
# 2. Generates operator keys (deterministic for testing)
# 3. Creates .env file with all configuration
#
# Usage: ./scripts/setup.sh or 'make setup'

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo "═══════════════════════════════════════════════════════════════════"
echo "Operator Setup"
echo "═══════════════════════════════════════════════════════════════════"
echo ""

# Configuration
OPERATOR_COUNT=${OPERATOR_COUNT:-3}

# Create directories
echo "Step 1: Creating directories..."
mkdir -p "${PROJECT_DIR}/data/anvil-source"
mkdir -p "${PROJECT_DIR}/data/anvil-dest"
mkdir -p "${PROJECT_DIR}/data/deploy-data"
mkdir -p "${PROJECT_DIR}/data/oz-monitor"
mkdir -p "${PROJECT_DIR}/symbiotic-relay/config"
for i in $(seq 1 $OPERATOR_COUNT); do
    mkdir -p "${PROJECT_DIR}/data/sidecar-${i}"
done
mkdir -p "${PROJECT_DIR}/config/oz-relayer/keys"
mkdir -p "${PROJECT_DIR}/config/oz-relayer/networks"
echo "  Directories created."
echo ""

# Generate operator keys
echo "Step 2: Generating operator keys..."

# Generate per-operator private keys.
# Prefer existing OPERATOR_N_PRIVATE_KEY env vars; otherwise generate random keys.
OPERATOR_KEYS=()
for i in $(seq 1 $OPERATOR_COUNT); do
    env_var="OPERATOR_${i}_PRIVATE_KEY"
    existing_key="${!env_var:-}"
    if [[ -n "$existing_key" ]]; then
        OPERATOR_KEYS+=("$existing_key")
    else
        # Generate a random 256-bit private key
        random_hex="0x$(openssl rand -hex 32)"
        OPERATOR_KEYS+=("$random_hex")
    fi
done

for i in $(seq 1 $OPERATOR_COUNT); do
    idx=$((i - 1))
    PRIVATE_KEY_HEX="${OPERATOR_KEYS[$idx]#0x}"

    # Derive EVM address from private key
    if command -v cast &> /dev/null; then
        EVM_ADDR=$(cast wallet address "0x${PRIVATE_KEY_HEX}" 2>/dev/null || echo "unknown")
    else
        EVM_ADDR="(cast not available)"
    fi

    echo "  Operator ${i}:"
    echo "    Private Key: 0x${PRIVATE_KEY_HEX:0:8}...${PRIVATE_KEY_HEX: -8}"
    echo "    EVM Address: ${EVM_ADDR}"
done
echo ""

# Create OZ Relayer keystores (aligned with operator keys)
echo "Step 3: Creating OZ Relayer keystores..."

SIGNER_KEYS=()
SIGNER_ADDRESSES=()

for i in 1 2 3; do
    idx=$((i - 1))
    key_hex="${OPERATOR_KEYS[$idx]}"
    SIGNER_KEYS+=("$key_hex")
    if command -v cast &> /dev/null; then
        signer_addr=$(cast wallet address --private-key "$key_hex" 2>/dev/null || echo "unknown")
    else
        signer_addr="(cast not available)"
    fi
    SIGNER_ADDRESSES+=("$signer_addr")
done

KEYSTORE_PASSPHRASE="${KEYSTORE_PASSPHRASE:-test-passphrase}"

if command -v cast &> /dev/null; then
    for i in 1 2 3; do
        idx=$((i - 1))
        KEYSTORE_FILE="${PROJECT_DIR}/config/oz-relayer/keys/signer-${i}.json"
        rm -f "${KEYSTORE_FILE}"

        cast wallet import \
            --keystore-dir "${PROJECT_DIR}/config/oz-relayer/keys" \
            --private-key "${SIGNER_KEYS[$idx]}" \
            --unsafe-password "${KEYSTORE_PASSPHRASE}" \
            "signer-${i}" 2>/dev/null || true

        # Rename if needed (cast creates without .json extension)
        mv "${PROJECT_DIR}/config/oz-relayer/keys/signer-${i}" "${KEYSTORE_FILE}" 2>/dev/null || true

        echo "  Signer ${i}:"
        echo "    Keystore: ${KEYSTORE_FILE}"
        echo "    Address:  ${SIGNER_ADDRESSES[$idx]}"
    done
else
    echo "  WARNING: cast not found, skipping keystore creation"
fi
echo ""

# Create .env file
echo "Step 4: Creating .env file..."
cat > "${PROJECT_DIR}/.env" << EOF
# Operator Environment Configuration
# Generated by scripts/setup.sh on $(date)

# ═══════════════════════════════════════════════════════════════════════════════
# General
# ═══════════════════════════════════════════════════════════════════════════════

LOG_LEVEL=info
PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

# Relay timing (required — production defaults are too slow for dev/testnet)
EPOCH_DURATION=60
SLASHING_WINDOW=60

# ═══════════════════════════════════════════════════════════════════════════════
# OZ Monitor (event watching)
# ═══════════════════════════════════════════════════════════════════════════════

WEBHOOK_URL=http://operator:3000/webhook/events
WEBHOOK_SECRET=test-webhook-secret-32-chars-minimum
METRICS_ENABLED=false

# ═══════════════════════════════════════════════════════════════════════════════
# OZ Relayer (transaction submission)
# ═══════════════════════════════════════════════════════════════════════════════

OZ_RELAYER_API_KEY=test-api-key-that-is-at-least-32-chars-long
OZ_RELAYER_WEBHOOK_SECRET=test-webhook-secret-32-chars-minimum
KEYSTORE_PASSPHRASE=${KEYSTORE_PASSPHRASE}

# Signer addresses (derived from operator private keys)
SIGNER_1_ADDRESS=${SIGNER_ADDRESSES[0]}
SIGNER_2_ADDRESS=${SIGNER_ADDRESSES[1]}
SIGNER_3_ADDRESS=${SIGNER_ADDRESSES[2]}

# ═══════════════════════════════════════════════════════════════════════════════
# Operator Private Keys
# Each operator has its own EVM/BLS private key. BLS keys are derived from these.
# ═══════════════════════════════════════════════════════════════════════════════

OPERATOR_COUNT=${OPERATOR_COUNT}
OPERATOR_1_PRIVATE_KEY=${OPERATOR_KEYS[0]}
OPERATOR_2_PRIVATE_KEY=${OPERATOR_KEYS[1]}
OPERATOR_3_PRIVATE_KEY=${OPERATOR_KEYS[2]}
EOF
echo "  .env created"
echo ""

# Output summary
echo "═══════════════════════════════════════════════════════════════════"
echo "Setup Complete!"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Next steps:"
echo ""
echo "  1. Start the stack:"
echo "     make start"
echo ""
echo "  2. Check status:"
echo "     make status"
echo ""
echo "  3. View logs:"
echo "     make logs-operators"
echo ""
echo "  4. Run E2E test:"
echo "     make test"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
