#!/bin/bash
# Setup script for Operator
#
# This script:
# 1. Creates directory structure
# 2. Generates operator keys (deterministic for testing)
# 3. Creates .env file with all configuration
#
# Usage: ./scripts/setup.sh or 'make setup'

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo "═══════════════════════════════════════════════════════════════════"
echo "Operator Setup"
echo "═══════════════════════════════════════════════════════════════════"
echo ""

# Configuration
OPERATOR_COUNT=${OPERATOR_COUNT:-3}
BASE_KEY="${OPERATOR_BASE_KEY:-1000000000000000000}"

# Create directories
echo "Step 1: Creating directories..."
mkdir -p "${PROJECT_DIR}/data/anvil-source"
mkdir -p "${PROJECT_DIR}/data/anvil-dest"
mkdir -p "${PROJECT_DIR}/data/deploy-data"
mkdir -p "${PROJECT_DIR}/data/oz-monitor"
mkdir -p "${PROJECT_DIR}/symbiotic-relay/config"
for i in $(seq 1 $OPERATOR_COUNT); do
    mkdir -p "${PROJECT_DIR}/data/sidecar-${i}"
done
mkdir -p "${PROJECT_DIR}/config/oz-relayer/keys"
mkdir -p "${PROJECT_DIR}/config/oz-relayer/networks"
echo "  Directories created."
echo ""

# Generate operator keys
echo "Step 2: Generating operator keys..."

# Swarm key for P2P (shared across all relays for network topic)
SWARM_KEY="FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364140"

for i in $(seq 1 $OPERATOR_COUNT); do
    KEY_INDEX=$((i - 1))
    PRIVATE_KEY_DECIMAL=$((BASE_KEY + KEY_INDEX))
    SECONDARY_KEY_DECIMAL=$((BASE_KEY + KEY_INDEX + 10000))

    PRIVATE_KEY_HEX=$(printf "%064x" $PRIVATE_KEY_DECIMAL)
    SECONDARY_KEY_HEX=$(printf "%064x" $SECONDARY_KEY_DECIMAL)

    # Build full secret keys for this operator including P2P keys for aggregation
    # Format: type/network/tag/key
    # - symb/0/15/: Primary BLS key for quorum signatures (tag 15 = BLS-BN254)
    # - symb/0/11/: Secondary BLS key
    # - symb/1/0/: Symbiotic network key
    # - evm/1/31337/: ECDSA key for source chain
    # - evm/1/31338/: ECDSA key for dest chain
    # - p2p/1/0/: Swarm key for libp2p (shared network topic)
    # - p2p/1/1/: Identity key for libp2p (unique per node for peer discovery)
    KEYS="symb/0/15/0x${PRIVATE_KEY_HEX},symb/0/11/0x${SECONDARY_KEY_HEX},symb/1/0/0x${PRIVATE_KEY_HEX},evm/1/31337/0x${PRIVATE_KEY_HEX},evm/1/31338/0x${PRIVATE_KEY_HEX},p2p/1/0/${SWARM_KEY},p2p/1/1/${PRIVATE_KEY_HEX}"

    # Derive EVM address from private key
    if command -v cast &> /dev/null; then
        EVM_ADDR=$(cast wallet address "0x${PRIVATE_KEY_HEX}" 2>/dev/null || echo "unknown")
    else
        EVM_ADDR="(cast not available)"
    fi

    echo "  Operator ${i}:"
    echo "    Private Key: 0x${PRIVATE_KEY_HEX:0:8}...${PRIVATE_KEY_HEX: -8}"
    echo "    EVM Address: ${EVM_ADDR}"

    # Store for .env file
    eval "SIDECAR_${i}_SECRET_KEYS='${KEYS}'"
done
echo ""

# Create OZ Relayer keystores (aligned with operator keys)
echo "Step 3: Creating OZ Relayer keystores..."

SIGNER_KEYS=()
SIGNER_ADDRESSES=()

for i in 1 2 3; do
    key_decimal=$((BASE_KEY + i - 1))
    key_hex=$(printf "0x%064x" "$key_decimal")
    SIGNER_KEYS+=("$key_hex")
    if command -v cast &> /dev/null; then
        signer_addr=$(cast wallet address --private-key "$key_hex" 2>/dev/null || echo "unknown")
    else
        signer_addr="(cast not available)"
    fi
    SIGNER_ADDRESSES+=("$signer_addr")
done

KEYSTORE_PASSPHRASE="${KEYSTORE_PASSPHRASE:-test-passphrase}"

if command -v cast &> /dev/null; then
    for i in 1 2 3; do
        idx=$((i - 1))
        KEYSTORE_FILE="${PROJECT_DIR}/config/oz-relayer/keys/signer-${i}.json"
        rm -f "${KEYSTORE_FILE}"

        cast wallet import \
            --keystore-dir "${PROJECT_DIR}/config/oz-relayer/keys" \
            --private-key "${SIGNER_KEYS[$idx]}" \
            --unsafe-password "${KEYSTORE_PASSPHRASE}" \
            "signer-${i}" 2>/dev/null || true

        # Rename if needed (cast creates without .json extension)
        mv "${PROJECT_DIR}/config/oz-relayer/keys/signer-${i}" "${KEYSTORE_FILE}" 2>/dev/null || true

        echo "  Signer ${i}:"
        echo "    Keystore: ${KEYSTORE_FILE}"
        echo "    Address:  ${SIGNER_ADDRESSES[$idx]}"
    done
else
    echo "  WARNING: cast not found, skipping keystore creation"
fi
echo ""

# Create .env file
echo "Step 4: Creating .env file..."
cat > "${PROJECT_DIR}/.env" << EOF
# Operator Environment Configuration
# Generated by scripts/setup.sh on $(date)

# ═══════════════════════════════════════════════════════════════════════════════
# General
# ═══════════════════════════════════════════════════════════════════════════════

LOG_LEVEL=info
PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

# ═══════════════════════════════════════════════════════════════════════════════
# OZ Monitor (event watching)
# ═══════════════════════════════════════════════════════════════════════════════

WEBHOOK_URL=http://operator:3000/webhook/events
WEBHOOK_SECRET=test-webhook-secret-32-chars-minimum
METRICS_ENABLED=false

# ═══════════════════════════════════════════════════════════════════════════════
# OZ Relayer (transaction submission)
# ═══════════════════════════════════════════════════════════════════════════════

OZ_RELAYER_API_KEY=test-api-key-that-is-at-least-32-chars-long
OZ_RELAYER_WEBHOOK_SECRET=test-webhook-secret-32-chars-minimum
KEYSTORE_PASSPHRASE=${KEYSTORE_PASSPHRASE}

# Signer addresses (aligned with OPERATOR_BASE_KEY)
SIGNER_1_ADDRESS=${SIGNER_ADDRESSES[0]}
SIGNER_2_ADDRESS=${SIGNER_ADDRESSES[1]}
SIGNER_3_ADDRESS=${SIGNER_ADDRESSES[2]}

# ═══════════════════════════════════════════════════════════════════════════════
# Symbiotic Relay Sidecars (BLS signing)
# ═══════════════════════════════════════════════════════════════════════════════

OPERATOR_COUNT=${OPERATOR_COUNT}
SIDECAR_1_SECRET_KEYS=${SIDECAR_1_SECRET_KEYS}
SIDECAR_2_SECRET_KEYS=${SIDECAR_2_SECRET_KEYS}
SIDECAR_3_SECRET_KEYS=${SIDECAR_3_SECRET_KEYS}
EOF
echo "  .env created"
echo ""

# Output summary
echo "═══════════════════════════════════════════════════════════════════"
echo "Setup Complete!"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Next steps:"
echo ""
echo "  1. Start the stack:"
echo "     make start"
echo ""
echo "  2. Check status:"
echo "     make status"
echo ""
echo "  3. View logs:"
echo "     make logs-operators"
echo ""
echo "  4. Run E2E test:"
echo "     make test"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
