#!/bin/bash
set -e

# =============================================================================
# Symbiotic LayerZero DVN - Network Generation Script
# =============================================================================
#
# This script generates the configuration files needed to run a local devnet
# with Symbiotic relay infrastructure and LayerZero DVN.
#
# Usage:
#   ./generate_network.sh
#   ./generate_network.sh --operators 4
#
# =============================================================================

# Change to script directory (devnet/)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Default configuration
DEFAULT_OPERATORS=4

# Parse arguments
OPERATORS=${OPERATORS:-$DEFAULT_OPERATORS}

while [[ $# -gt 0 ]]; do
    case $1 in
        --operators)
            OPERATORS="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

echo "=== Symbiotic LayerZero DVN Network Generator ==="
echo "Operators: $OPERATORS"
echo ""

# Create directories
RELAY_CONFIG_DIR="relay-config"
DEPLOY_DATA_DIR="deploy-data"
STORAGE_DIR="storage"

mkdir -p "$RELAY_CONFIG_DIR"
mkdir -p "$DEPLOY_DATA_DIR"
mkdir -p "$STORAGE_DIR"

# Create storage directories for each operator
for i in $(seq 1 $OPERATORS); do
    mkdir -p "$STORAGE_DIR/sidecar-$i"
done

echo "Created directories:"
echo "  - $RELAY_CONFIG_DIR"
echo "  - $DEPLOY_DATA_DIR"
echo "  - $STORAGE_DIR"

# =============================================================================
# Generate operator keys
# =============================================================================

echo ""
echo "Generating operator keys..."

# Base private key (deterministic for testing)
BASE_PRIVATE_KEY=1000000000000000000

OPERATOR_KEYS=()
SECRET_KEYS_ARGS=()

for i in $(seq 0 $((OPERATORS - 1))); do
    # Generate deterministic private key
    KEY_DECIMAL=$((BASE_PRIVATE_KEY + i))
    PRIVATE_KEY=$(printf '%064x' $KEY_DECIMAL)
    OPERATOR_KEYS+=("0x$PRIVATE_KEY")

    # Build secret keys argument for relay sidecar
    # Format: protocol/chain/keytype/0xkey
    # symb/0/15 = BLS-BN254 key (tag 15)
    # evm/1/31337 = EVM key for chain 31337
    # evm/1/31338 = EVM key for chain 31338
    SECRET_KEYS_ARGS+=("symb/0/15/0x$PRIVATE_KEY,evm/1/31337/0x$PRIVATE_KEY,evm/1/31338/0x$PRIVATE_KEY")

    echo "  Operator $i: 0x${PRIVATE_KEY:0:8}..."
done

# =============================================================================
# Generate sidecar YAML configs
# =============================================================================

echo ""
echo "Generating sidecar configs..."

# Bootstrap peers list (all sidecars connect to each other)
BOOTSTRAP_PEERS=""
for i in $(seq 1 $OPERATORS); do
    if [ -n "$BOOTSTRAP_PEERS" ]; then
        BOOTSTRAP_PEERS="$BOOTSTRAP_PEERS,"
    fi
    BOOTSTRAP_PEERS="$BOOTSTRAP_PEERS\"/dns4/relay-sidecar-$i/tcp/8880\""
done

for i in $(seq 1 $OPERATORS); do
    IDX=$((i - 1))

    cat > "$RELAY_CONFIG_DIR/sidecar-$i.yaml" << EOF
driver:
  chain-id: 31337
  address: "0x0000000000000000000000000000000000000000"
log:
  level: debug
  mode: pretty
signer: true
evm:
  chains:
    - "http://anvil-source:8545"
    - "http://anvil-dest:8545"
api:
  listen: "0.0.0.0:8080"
p2p:
  listen: "/ip4/0.0.0.0/tcp/8880"
  mdns: true
  bootnodes:
EOF

    # Add bootstrap peers (excluding self)
    for j in $(seq 1 $OPERATORS); do
        if [ "$j" != "$i" ]; then
            echo "    - \"/dns4/relay-sidecar-$j/tcp/8880\"" >> "$RELAY_CONFIG_DIR/sidecar-$i.yaml"
        fi
    done

    echo "  Created: $RELAY_CONFIG_DIR/sidecar-$i.yaml"
done

# =============================================================================
# Generate .env file for docker compose
# =============================================================================

echo ""
echo "Generating .env file..."

cat > ".env" << EOF
# Symbiotic LayerZero DVN - Environment Configuration
# Generated by generate_network.sh

# Number of operators
OPERATOR_COUNT=$OPERATORS

# Operator private keys (first operator used for DVN worker)
OPERATOR_PRIVATE_KEY=${OPERATOR_KEYS[0]}

# Secret keys for each sidecar (protocol/chain/keytype/key format)
EOF

for i in $(seq 1 $OPERATORS); do
    IDX=$((i - 1))
    echo "SIDECAR_${i}_SECRET_KEYS=\"${SECRET_KEYS_ARGS[$IDX]}\"" >> "devnet/.env"
done

cat >> "devnet/.env" << EOF

# Contract addresses (populated after deployment)
# SOURCE_DVN_ADDRESS=
# DEST_DVN_ADDRESS=

# Chain configuration
SOURCE_CHAIN_ID=31337
DEST_CHAIN_ID=31338
SOURCE_EID=31337
DEST_EID=31338
EOF

echo "  Created: .env"

# =============================================================================
# Generate genesis-generator script
# =============================================================================

echo ""
echo "Generating genesis-generator script..."

cat > "$RELAY_CONFIG_DIR/genesis-generator.sh" << 'EOF'
#!/bin/sh
set -e

echo "Waiting for deployment to complete..."
until [ -f /deploy-data/deployment-complete.marker ]; do
    sleep 2
done

echo "Waiting for driver_contracts.json..."
until [ -f /deploy-data/driver_contracts.json ]; do
    sleep 2
done

# Extract driver address using sed (alpine-compatible)
DRIVER_ADDRESS=$(sed -n 's/.*"addr"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' /deploy-data/driver_contracts.json | head -1)
echo "Driver address: $DRIVER_ADDRESS"

MAX_RETRIES=30
RETRY_DELAY=3
attempt=1

while [ $attempt -le $MAX_RETRIES ]; do
    echo "Attempt $attempt of $MAX_RETRIES: Generating network genesis..."

    if /app/relay_utils network \
            --chains http://anvil-source:8545,http://anvil-dest:8545 \
            --driver-address "$DRIVER_ADDRESS" \
            --driver-chainid 31337 \
          generate-genesis \
            --commit \
            --secret-keys 31337:0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80,31338:0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80; then
        echo "Genesis generation completed successfully!"
        echo "$(date)" > /deploy-data/genesis-complete.marker
        exit 0
    else
        echo "Genesis generation failed on attempt $attempt"
        if [ $attempt -lt $MAX_RETRIES ]; then
            echo "Waiting $RETRY_DELAY seconds before retry..."
            sleep $RETRY_DELAY
        else
            echo "All $MAX_RETRIES attempts failed."
            exit 1
        fi
        attempt=$((attempt + 1))
    fi
done
EOF
chmod +x "$RELAY_CONFIG_DIR/genesis-generator.sh"
echo "  Created: $RELAY_CONFIG_DIR/genesis-generator.sh"

# =============================================================================
# Generate sidecar start scripts
# =============================================================================

echo ""
echo "Generating sidecar start scripts..."

for i in $(seq 1 $OPERATORS); do
    cat > "$RELAY_CONFIG_DIR/start-sidecar-$i.sh" << 'SCRIPT_HEADER'
#!/bin/sh
set -e

# Extract driver address from deployment data
DRIVER_ADDRESS=$(sed -n 's/.*"addr"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' /deploy-data/driver_contracts.json | head -1)
echo "Starting sidecar with driver: $DRIVER_ADDRESS"

# Create config with actual driver address
cat > /tmp/sidecar.yaml << YAMLEOF
driver:
  chain-id: 31337
  address: "$DRIVER_ADDRESS"
log:
  level: debug
  mode: pretty
signer: true
evm:
  chains:
    - "http://anvil-source:8545"
    - "http://anvil-dest:8545"
api:
  listen: "0.0.0.0:8080"
p2p:
  listen: "/ip4/0.0.0.0/tcp/8880"
  mdns: true
  bootnodes:
SCRIPT_HEADER

    # Add bootstrap peers (excluding self)
    for j in $(seq 1 $OPERATORS); do
        if [ "$j" != "$i" ]; then
            echo "    - \"/dns4/relay-sidecar-$j/tcp/8880\"" >> "$RELAY_CONFIG_DIR/start-sidecar-$i.sh"
        fi
    done

    cat >> "$RELAY_CONFIG_DIR/start-sidecar-$i.sh" << EOF
YAMLEOF

exec /app/relay_sidecar \\
    --config /tmp/sidecar.yaml \\
    --secret-keys "\$SIDECAR_${i}_SECRET_KEYS" \\
    --storage-dir /storage
EOF

    chmod +x "$RELAY_CONFIG_DIR/start-sidecar-$i.sh"
    echo "  Created: $RELAY_CONFIG_DIR/start-sidecar-$i.sh"
done

# =============================================================================
# Summary
# =============================================================================

echo ""
echo "=== Network Generation Complete ==="
echo ""
echo "Configuration files created in: $RELAY_CONFIG_DIR/"
echo ""
echo "Next steps:"
echo "  ./devnet.sh up"
echo ""
